"""Log-mel spectrogram for training — must match web/src/inference/mel.ts exactly so the
encoder sees the same input in Python (training) and the browser (inference).

Conventions mirror mel.ts and are pinned by the golden-vector test
(web/src/inference/mel-parity.test.ts): periodic Hann window, center=False framing, power
spectrum, HTK mel scale, triangular filters with no area normalization, log(mel + 1e-6).
Output is [N_MELS, N_FRAMES] (mel-major); flattened C-order it matches the ONNX input
[1, 1, N_MELS, N_FRAMES] and mel.ts's flat Float32Array.

    python -m training.data.mel --write-golden   # (re)generate schema/mel-golden.json
    python -m training.data.mel --check          # assert mel.py still matches the golden
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from training import schema

SR = schema.AUDIO["sample_rate"]
N_FFT = schema.AUDIO["n_fft"]
HOP = schema.AUDIO["hop_length"]
N_MELS = schema.N_MELS
FMIN = schema.AUDIO["fmin"]
FMAX = schema.AUDIO["fmax"]
N_FRAMES = schema.N_FRAMES
N_FREQS = N_FFT // 2 + 1

_SCHEMA_DIR = Path(__file__).resolve().parents[2] / "schema"
_GOLDEN = _SCHEMA_DIR / "mel-golden.json"

# Deterministic reference signal (sum of sines) — reproducible identically in JS doubles.
_REFERENCE = {
    "sample_rate": SR,
    "length": schema.N_SAMPLES,
    "tones": [[220.0, 0.6], [440.0, 0.3], [880.0, 0.1]],
}


def _hz_to_mel(hz: np.ndarray | float) -> np.ndarray | float:
    return 2595.0 * np.log10(1.0 + np.asarray(hz) / 700.0)


def _mel_to_hz(mel: np.ndarray | float) -> np.ndarray | float:
    return 700.0 * (10.0 ** (np.asarray(mel) / 2595.0) - 1.0)


def _hann(n: int) -> np.ndarray:
    return 0.5 * (1.0 - np.cos(2.0 * np.pi * np.arange(n) / n))


def _filterbank() -> np.ndarray:
    mel_min, mel_max = _hz_to_mel(FMIN), _hz_to_mel(FMAX)
    edges = _mel_to_hz(mel_min + (mel_max - mel_min) * np.arange(N_MELS + 2) / (N_MELS + 1))
    fft_freq = np.arange(N_FREQS) * SR / N_FFT
    fb = np.zeros((N_MELS, N_FREQS), dtype=np.float64)
    for m in range(1, N_MELS + 1):
        left, center, right = edges[m - 1], edges[m], edges[m + 1]
        for k in range(N_FREQS):
            f = fft_freq[k]
            if left <= f <= center:
                fb[m - 1, k] = (f - left) / (center - left)
            elif center < f <= right:
                fb[m - 1, k] = (right - f) / (right - center)
    return fb


_WINDOW = _hann(N_FFT)
_FILTERBANK = _filterbank()


def log_mel(signal: np.ndarray) -> np.ndarray:
    """Mono signal (>= N_SAMPLES) -> float32 [N_MELS, N_FRAMES]."""
    out = np.empty((N_MELS, N_FRAMES), dtype=np.float32)
    for frame in range(N_FRAMES):
        start = frame * HOP
        seg = signal[start : start + N_FFT] * _WINDOW
        spec = np.fft.rfft(seg, n=N_FFT)
        power = spec.real**2 + spec.imag**2
        out[:, frame] = np.log(_FILTERBANK @ power + 1e-6)
    return out


def reference_signal(spec: dict = _REFERENCE) -> np.ndarray:
    i = np.arange(spec["length"], dtype=np.float64)
    sig = np.zeros(spec["length"], dtype=np.float64)
    for freq, amp in spec["tones"]:
        sig += amp * np.sin(2.0 * np.pi * freq * i / spec["sample_rate"])
    # Round to float32 so the input matches the browser's Float32Array bit-for-bit; only
    # the FFT's internal precision then differs between the two implementations.
    return sig.astype(np.float32).astype(np.float64)


def build_golden() -> dict:
    mel = log_mel(reference_signal())
    return {
        "note": "Generated by `python -m training.data.mel --write-golden`. Pins "
        "training/data/mel.py <-> web/src/inference/mel.ts parity.",
        "signal": _REFERENCE,
        "n_mels": N_MELS,
        "n_frames": N_FRAMES,
        "mel": mel.flatten().tolist(),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--write-golden", action="store_true")
    group.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if args.write_golden:
        _GOLDEN.write_text(json.dumps(build_golden()))
        print(f"wrote {_GOLDEN}")
    else:
        golden = json.loads(_GOLDEN.read_text())
        mel = log_mel(reference_signal(golden["signal"])).flatten()
        diff = float(np.max(np.abs(mel - np.array(golden["mel"], dtype=np.float32))))
        assert diff == 0.0, f"mel.py drifted from the golden (max diff {diff})"
        print(f"mel.py matches golden (max diff {diff})")


if __name__ == "__main__":
    main()
